In [2]:
# conda create -n pytorch_practice python=3.10.12
# conda activate pytorch_practice
# conda install jupyter pandas numpy matplotlib scikit-learn tqdm pip

In [4]:
import torch
import numpy as np
import pandas as pd
import sklearn
import matplotlib.pyplot as plt
import sys

print(f"Python version: {sys.version}")
print(f"PyTorch version: {torch.__version__}")

# Check PyTorch has access to MPS (Metal Performance Shader, Apple's GPU architecture)
print(f"Is MPS (Metal Performance Shader) built? {torch.backends.mps.is_built()}")
print(f"Is MPS available? {torch.backends.mps.is_available()}")

# Set the device      
device = "mps" if torch.backends.mps.is_available() else "cpu"
print(f"Using device: {device}")

Python version: 3.10.12 (main, Jul  5 2023, 15:02:25) [Clang 14.0.6 ]
PyTorch version: 2.0.1
Is MPS (Metal Performance Shader) built? True
Is MPS available? True
Using device: mps


In [7]:
# Tensors

# Create a tensor from a list

# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [8]:
scalar.ndim

0

In [9]:
# tensor back as python int
scalar.item()

7

In [10]:
vector = torch.tensor([1, 2, 3, 4])
vector

tensor([1, 2, 3, 4])

In [11]:
vector.ndim

1

In [12]:
vector.shape

torch.Size([4])

In [14]:
# MATRIX
MATRIX = torch.tensor([[1, 2, 3],
                          [4, 5, 6]])
MATRIX

tensor([[1, 2, 3],
        [4, 5, 6]])

In [15]:
MATRIX.ndim

2

In [16]:
MATRIX[0]

tensor([1, 2, 3])

In [20]:
MATRIX[1][2]

tensor(6)

In [21]:
MATRIX.shape

torch.Size([2, 3])

In [43]:
# # Tensor
# TENSOR = torch.tensor([[[1, 2, 3],
#                         [4, 5, 6],
#                           [7, 8, 9],
#                             [10, 11, 12]]])

# # Tensor
TENSOR = torch.tensor([[[[[1, 2, 3],
                        [4, 5, 6]]],
                          [[[7, 8, 9],
                            [10, 11, 12]]]],
                            [[[[1, 2, 3],
                        [4, 5, 6]]],
                          [[[7, 8, 9],
                            [10, 11, 12]]]]])


TENSOR

tensor([[[[[ 1,  2,  3],
           [ 4,  5,  6]]],


         [[[ 7,  8,  9],
           [10, 11, 12]]]],



        [[[[ 1,  2,  3],
           [ 4,  5,  6]]],


         [[[ 7,  8,  9],
           [10, 11, 12]]]]])

In [44]:
TENSOR.ndim

5

In [45]:
TENSOR.shape

torch.Size([2, 2, 1, 2, 3])

In [47]:
# TENSOR[0]

In [51]:
# Random tensors
# Why random tensors?
# Random tensors are important because the way many neural networks are initialized is by generating a bunch of random tensors 
# and then updating those tensors based on the patterns found in the data.

# Create a random tensor
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.3255, 0.8612, 0.5153, 0.2217],
        [0.9219, 0.9068, 0.4543, 0.5823],
        [0.7787, 0.6248, 0.8373, 0.0350]])

In [53]:
random_image_size_tensor = torch.rand(size=(3, 224, 224))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [57]:
# zeroes and ones tensors
# Create a tensor of all zeros
zeros = torch.zeros(3, 4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [58]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [59]:
# Create a tensor of all ones
ones = torch.ones(3, 4)

In [60]:
ones*random_tensor

tensor([[0.3255, 0.8612, 0.5153, 0.2217],
        [0.9219, 0.9068, 0.4543, 0.5823],
        [0.7787, 0.6248, 0.8373, 0.0350]])

In [61]:
ones.dtype

torch.float32

In [62]:
random_tensor.dtype

torch.float32

In [68]:
# Create a range of tensors and tensors-like
tensor_range = torch.arange(start=0, end=10, step=3)
tensor_range

tensor([0, 3, 6, 9])

In [73]:
# Creating tensors like
tensor_range2 = torch.zeros_like(input=tensor_range)
# torch.ones_like(input=tensor_range)
# torch.rand_like(input=tensor_range, dtype=torch.float32)

tensor_range2

tensor([0, 0, 0, 0])

# Tensor datatypes

Note: tensor datatypes is one of the 3 big errors you'll run into with Pytorch & deep learning
1. tensors not right data type
2. tensors not right shape
3. tensors not right device

In [82]:
# Tensor datatypes
float_16_tensor = torch.tensor([1, 2, 3],
                               dtype=None, # what datatype is the tensor
                               device="mps", # where to store the tensor (CPU or GPU)
                               requires_grad=False) # whether or not to track gradient operations of these tensors

float_16_tensor

tensor([1, 2, 3], device='mps:0')

In [84]:
float_32_tensor = float_16_tensor.to(dtype=torch.float32)

In [85]:
float_32_tensor.dtype

torch.float32

In [86]:
float_32_tensor*float_16_tensor

tensor([1., 4., 9.], device='mps:0')

In [96]:
int32_tensor = torch.tensor([1, 2, 3], dtype=torch.long)
int32_tensor

tensor([1, 2, 3])

In [92]:
float_32_tensor*int32_tensor

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, mps:0 and cpu!

### getting information from tensors

1. To get datatype, use "tensor.dtype"
2. To get shape, use "tensor.shape"
3. To get dimension, use "tensor.ndim"
4. To get device, use "tensor.device"

In [100]:
random_tensor = torch.rand(3, 4)
random_tensor.dtype

torch.float32

In [101]:
random_tensor.shape, random_tensor.size()

(torch.Size([3, 4]), torch.Size([3, 4]))

### Manipulating tensors (tensor operations)

Tensor operations include:
- addition
- subtraction
- multiplication (element-wise)
- division
- matric multiplication

In [115]:
tensor = torch.tensor([1, 2, 3])
# tensor + 10
# tensor * 10
# tensor - 10
# tensor / 10
# torch.add(tensor, 10)
# torch.mul(tensor, 10)
# torch.sub(tensor, 10)
torch.div(tensor, 10)

tensor([0.1000, 0.2000, 0.3000])

### Matrix multiplication

2 main ways of multiplication in NN and Deep Learning

1. element wise multiplication
2. matrix multiplication (dot product)

2 main rules that matrix multipliction needs to satisfy
1. The **inner dimensions** must match:
* `(3,2) @ (2,6)`

2. The resulting matrix has the shape of the outer dimensions.

In [118]:
print(tensor, "*", tensor)
print(f"Equals: {torch.mul(tensor, tensor)}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [119]:
torch.matmul(tensor, tensor)

tensor(14)

In [122]:
%%time

value=0
for i in range(len(tensor)):
    value += tensor[i]*tensor[i]
print(f"Equals: {value}")

Equals: 14
CPU times: user 860 µs, sys: 1.54 ms, total: 2.4 ms
Wall time: 1.93 ms


In [124]:
%%time

torch.matmul(tensor, tensor)

CPU times: user 206 µs, sys: 41 µs, total: 247 µs
Wall time: 208 µs


tensor(14)

In [133]:
### One of the most common errors in deep learning is shape errors

# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                          [3, 4],
                          [5, 6]])

tensor_B = torch.tensor([[7, 10],
                          [8, 11],
                          [9, 12]])

In [134]:
# torch.mm is the same as torch.matmul

torch.mm(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [135]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape using a **transpose**

A transpose switched the axis or dimensions of a given tensor

In [139]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [140]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [141]:
# The matrix multiplication works when tensor_B is transposed
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Finding the min max mean sum etc

In [147]:
# create a tensor
x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [143]:
# find the min
torch.argmin(x), x.min()
# torch.argmax(x), x.max()

tensor(0)

In [148]:
# torch.mean() requires the input tensor to be float32
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [149]:
# find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [151]:
x.argmin(), x.argmax()

(tensor(0), tensor(9))

### Reshaping, stacking, squeezing & unsqueezing tensors

- Reshaping - reshapes an input tensor to a defined shape
- View - return a view of an input tensor of a certain shape but keep the same memory as the original tensor
- Stacking - combining multiple tensors on top of each other (vstack) or side by side (hstack)
- Squueze - removes all '1' dimensions from a tensor
- Unsquueze - add a '1' dimensions to a target tensor

In [167]:
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [169]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [163]:
x_reshaped = x.reshape(9, 1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [170]:
# Change the view
z = x.view(1,9)
z, x.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([9]))

In [171]:
# Changing z changes x because a view shares the same memory as the original tensor
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [181]:
# Stack tensors on top
x_stacked = torch.stack([x, x, x], dim=1)
x_stacked, x_stacked.shape

(tensor([[5., 5., 5.],
         [2., 2., 2.],
         [3., 3., 3.],
         [4., 4., 4.],
         [5., 5., 5.],
         [6., 6., 6.],
         [7., 7., 7.],
         [8., 8., 8.],
         [9., 9., 9.]]),
 torch.Size([9, 3]))

In [186]:
# squeeze a tensor - removes all single dimensions from a targret tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous tensor shape: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_sqeezed = x_reshaped.squeeze()
print(f"New Squeezed tensor: {x_sqeezed}")
print(f"New Squeezed tensor shape: {x_sqeezed.shape}")


Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous tensor shape: torch.Size([1, 9])
New Squeezed tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New Squeezed tensor shape: torch.Size([9])


In [193]:
# add a dimension of 1 to a tensor's shape
# torch.unsqueeze()

print(f"Previous target: {x_sqeezed}")
print(f"Previous target shape: {x_sqeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqeezed = x_sqeezed.unsqueeze(dim=0)
print(f"New unsqueezed tensor: {x_unsqeezed}")
print(f"New unsqueezed tensor shape: {x_unsqeezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous target shape: torch.Size([9])
New unsqueezed tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New unsqueezed tensor shape: torch.Size([1, 9])


In [197]:
# Torch.permute() - rearranges the dimensions of a tensor
x_original = torch.rand(size=(224, 224, 3)) #[height, width, colour_chanels]

# Permute the original tensor to rearrange the axis ( or dim) order
x_permuted = x_original.permute(2, 0, 1) #[colour_chanels, height, width]

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [199]:
x_original[0, 0, 0] = 73982
x_original[0, 0, 0], x_permuted[0, 0, 0]

(tensor(73982.), tensor(73982.))

### Indexing (selecting data from tensors)

Indexsing with PTorch is similar to indexing with NumPy

In [203]:
# Create a tenssor
import torch
x = torch.arange(1, 10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [204]:
#Let's index on our tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [205]:
# Let's index on the middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [212]:
# Let's index on the most inner bracket (last dimension)
x[0][2][2]

tensor(9)

In [213]:
# You can also use ":" to select all items of a target dimensio
x[:,0]

tensor([[1, 2, 3]])

In [223]:
# Get all values of the 0th & 1st dimensions but only index 1 of 2nd dimension
x[:, :, 2]
# x[0, 2, :]

tensor([[3, 6, 9]])

In [229]:
# Get all values of the 0th dimension but only the 1 index value of 1st and 2nd dimensions
x[:, 1, 1], x[0, 1, 1]

(tensor([5]), tensor(5))

In [230]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]
# same as x[:,0]

tensor([1, 2, 3])

In [232]:
# Index on x to return 9
x[0, 2, 2]

# Index on x to return 3, 6, 9
x[0, :, 2]

tensor([3, 6, 9])

# Pytorch tensors & NumPy

NumPy is a popular scientific computing library.
And because of this, Pytorch has functionality to interact with it

* Data in NumPy, want in PyTorch tensor -> 'torch.from_numpy(ndarray)'
* PyTorch tensor -> NumPy -> torch.numpy()


In [242]:
# Numpy array to tensor
import torch
import numpy as np

array = np.arange(1, 8.0)
# tensor = torch.from_numpy(array) 
# warning: when converting from numpy to pytorch, pytorch reflects numpys default dtype of float64 unless specified
tensor = torch.from_numpy(array).type(torch.float32)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [243]:
array.dtype, tensor.dtype

(dtype('float64'), torch.float32)

In [244]:
# View the default dtype of a tensor
torch.arange(1,8.0).dtype

torch.float32

In [245]:
# Change the value of array, what will this do to a tensor?
array = array + 1
array, tensor
# Nothing changes in the tensor
# The tensor is created in new memory


(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [246]:
# Tensor to numpy array
tensor = torch.ones(7)
numpy_array = tensor.numpy()
tensor, numpy_array

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [247]:
numpy_array.dtype, tensor.dtype
# Keep in mind default of numpy is float64 and pytorch is float32

(dtype('float32'), torch.float32)

In [248]:
# Change the tensor
tensor = tensor + 1
tensor, numpy_array
# The numpy array does not share memory with the tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reporoducability - taking the random out of random

In short, how a NN learns:

`start with random numbers -> tensor operations -> update rand # -> again -> again..`

To reduce randomness in neural networks & pytorch comes the concept of **random seed**.

Essentially what the random seed is 'flavour' the randomness.

Extra resources: https://pytorch.org/docs/stable/notes/randomness.html

In [264]:
import torch

# Create two random tensors
torch.rand(3,3)
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(f"First random tensor: \n{random_tensor_A}")
print(f"Second random tensor: \n{random_tensor_B}\n")
print(random_tensor_A == random_tensor_B)

First random tensor: 
tensor([[0.7295, 0.8845, 0.7995, 0.3273],
        [0.0654, 0.4392, 0.9857, 0.3740],
        [0.9514, 0.4427, 0.8519, 0.7036]])
Second random tensor: 
tensor([[0.8035, 0.6494, 0.4401, 0.7423],
        [0.3843, 0.4088, 0.8408, 0.7236],
        [0.9272, 0.8986, 0.4642, 0.9059]])

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [269]:
# Let's make some random but reproducible tensors
import torch
# Set the random seed
RANDOM_SEED = 77
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)
print(f"First random tensor: \n{random_tensor_C}")
print(f"Second random tensor: \n{random_tensor_D}\n")
print(random_tensor_C == random_tensor_D)
# Random seed generally works only for 1 block of code so be careful.

First random tensor: 
tensor([[0.2919, 0.2857, 0.4021, 0.4645],
        [0.9503, 0.2564, 0.6645, 0.8609],
        [0.3538, 0.3347, 0.7285, 0.5794]])
Second random tensor: 
tensor([[0.2919, 0.2857, 0.4021, 0.4645],
        [0.9503, 0.2564, 0.6645, 0.8609],
        [0.3538, 0.3347, 0.7285, 0.5794]])

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [271]:
# Running tensors and Pytorch objects on the GPUs (and making faster computations)

# Use GPU if available
device = "mps" if torch.backends.mps.is_available() else "cpu"
print(f"Using device: {device}")

# Count the number of devices available
# torch.cuda.device_count()

Using device: mps


0

## Putting tensors and models on the GPU

The reason we want our tensors/models on the GPU is beacause usig a GPu results in faster computations.

In [272]:
tensor = torch.ones(10, 10)

tensor.device

device(type='cpu')

In [273]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu.device

device(type='mps', index=0)

## 4. Moving tensors back to the CPU

In [274]:
tensor_on_gpu.numpy()
# numpy doesnt work with GPUs

TypeError: can't convert mps:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [276]:
# To fix this, we can move our tensor back to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]], dtype=float32)

In [278]:
tensor_on_gpu

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]], device='mps:0')