In [2]:
# conda create -n pytorch_practice python=3.10.12
# conda activate pytorch_practice
# conda install jupyter pandas numpy matplotlib scikit-learn tqdm pip

In [4]:
import torch
import numpy as np
import pandas as pd
import sklearn
import matplotlib.pyplot as plt
import sys

print(f"Python version: {sys.version}")
print(f"PyTorch version: {torch.__version__}")

# Check PyTorch has access to MPS (Metal Performance Shader, Apple's GPU architecture)
print(f"Is MPS (Metal Performance Shader) built? {torch.backends.mps.is_built()}")
print(f"Is MPS available? {torch.backends.mps.is_available()}")

# Set the device      
device = "mps" if torch.backends.mps.is_available() else "cpu"
print(f"Using device: {device}")

Python version: 3.10.12 (main, Jul  5 2023, 15:02:25) [Clang 14.0.6 ]
PyTorch version: 2.0.1
Is MPS (Metal Performance Shader) built? True
Is MPS available? True
Using device: mps


In [7]:
# Tensors

# Create a tensor from a list

# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [8]:
scalar.ndim

0

In [9]:
# tensor back as python int
scalar.item()

7

In [10]:
vector = torch.tensor([1, 2, 3, 4])
vector

tensor([1, 2, 3, 4])

In [11]:
vector.ndim

1

In [12]:
vector.shape

torch.Size([4])

In [14]:
# MATRIX
MATRIX = torch.tensor([[1, 2, 3],
                          [4, 5, 6]])
MATRIX

tensor([[1, 2, 3],
        [4, 5, 6]])

In [15]:
MATRIX.ndim

2

In [16]:
MATRIX[0]

tensor([1, 2, 3])

In [20]:
MATRIX[1][2]

tensor(6)

In [21]:
MATRIX.shape

torch.Size([2, 3])

In [43]:
# # Tensor
# TENSOR = torch.tensor([[[1, 2, 3],
#                         [4, 5, 6],
#                           [7, 8, 9],
#                             [10, 11, 12]]])

# # Tensor
TENSOR = torch.tensor([[[[[1, 2, 3],
                        [4, 5, 6]]],
                          [[[7, 8, 9],
                            [10, 11, 12]]]],
                            [[[[1, 2, 3],
                        [4, 5, 6]]],
                          [[[7, 8, 9],
                            [10, 11, 12]]]]])


TENSOR

tensor([[[[[ 1,  2,  3],
           [ 4,  5,  6]]],


         [[[ 7,  8,  9],
           [10, 11, 12]]]],



        [[[[ 1,  2,  3],
           [ 4,  5,  6]]],


         [[[ 7,  8,  9],
           [10, 11, 12]]]]])

In [44]:
TENSOR.ndim

5

In [45]:
TENSOR.shape

torch.Size([2, 2, 1, 2, 3])

In [47]:
# TENSOR[0]

In [51]:
# Random tensors
# Why random tensors?
# Random tensors are important because the way many neural networks are initialized is by generating a bunch of random tensors 
# and then updating those tensors based on the patterns found in the data.

# Create a random tensor
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.3255, 0.8612, 0.5153, 0.2217],
        [0.9219, 0.9068, 0.4543, 0.5823],
        [0.7787, 0.6248, 0.8373, 0.0350]])

In [53]:
random_image_size_tensor = torch.rand(size=(3, 224, 224))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [57]:
# zeroes and ones tensors
# Create a tensor of all zeros
zeros = torch.zeros(3, 4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [58]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [59]:
# Create a tensor of all ones
ones = torch.ones(3, 4)

In [60]:
ones*random_tensor

tensor([[0.3255, 0.8612, 0.5153, 0.2217],
        [0.9219, 0.9068, 0.4543, 0.5823],
        [0.7787, 0.6248, 0.8373, 0.0350]])

In [61]:
ones.dtype

torch.float32

In [62]:
random_tensor.dtype

torch.float32

In [68]:
# Create a range of tensors and tensors-like
tensor_range = torch.arange(start=0, end=10, step=3)
tensor_range

tensor([0, 3, 6, 9])

In [73]:
# Creating tensors like
tensor_range2 = torch.zeros_like(input=tensor_range)
# torch.ones_like(input=tensor_range)
# torch.rand_like(input=tensor_range, dtype=torch.float32)

tensor_range2

tensor([0, 0, 0, 0])

# Tensor datatypes

Note: tensor datatypes is one of the 3 big errors you'll run into with Pytorch & deep learning
1. tensors not right data type
2. tensors not right shape
3. tensors not right device

In [82]:
# Tensor datatypes
float_16_tensor = torch.tensor([1, 2, 3],
                               dtype=None, # what datatype is the tensor
                               device="mps", # where to store the tensor (CPU or GPU)
                               requires_grad=False) # whether or not to track gradient operations of these tensors

float_16_tensor

tensor([1, 2, 3], device='mps:0')

In [84]:
float_32_tensor = float_16_tensor.to(dtype=torch.float32)

In [85]:
float_32_tensor.dtype

torch.float32

In [86]:
float_32_tensor*float_16_tensor

tensor([1., 4., 9.], device='mps:0')

In [96]:
int32_tensor = torch.tensor([1, 2, 3], dtype=torch.long)
int32_tensor

tensor([1, 2, 3])

In [92]:
float_32_tensor*int32_tensor

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, mps:0 and cpu!

### getting information from tensors

1. To get datatype, use "tensor.dtype"
2. To get shape, use "tensor.shape"
3. To get dimension, use "tensor.ndim"
4. To get device, use "tensor.device"

In [100]:
random_tensor = torch.rand(3, 4)
random_tensor.dtype

torch.float32

In [101]:
random_tensor.shape, random_tensor.size()

(torch.Size([3, 4]), torch.Size([3, 4]))

### Manipulating tensors (tensor operations)

Tensor operations include:
- addition
- subtraction
- multiplication (element-wise)
- division
- matric multiplication

In [115]:
tensor = torch.tensor([1, 2, 3])
# tensor + 10
# tensor * 10
# tensor - 10
# tensor / 10
# torch.add(tensor, 10)
# torch.mul(tensor, 10)
# torch.sub(tensor, 10)
torch.div(tensor, 10)

tensor([0.1000, 0.2000, 0.3000])

### Matrix multiplication

2 main ways of multiplication in NN and Deep Learning

1. element wise multiplication
2. matrix multiplication (dot product)

2 main rules that matrix multipliction needs to satisfy
1. The **inner dimensions** must match:
* `(3,2) @ (2,6)`

2. The resulting matrix has the shape of the outer dimensions.

In [118]:
print(tensor, "*", tensor)
print(f"Equals: {torch.mul(tensor, tensor)}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [119]:
torch.matmul(tensor, tensor)

tensor(14)

In [122]:
%%time

value=0
for i in range(len(tensor)):
    value += tensor[i]*tensor[i]
print(f"Equals: {value}")

Equals: 14
CPU times: user 860 µs, sys: 1.54 ms, total: 2.4 ms
Wall time: 1.93 ms


In [124]:
%%time

torch.matmul(tensor, tensor)

CPU times: user 206 µs, sys: 41 µs, total: 247 µs
Wall time: 208 µs


tensor(14)

In [133]:
### One of the most common errors in deep learning is shape errors

# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                          [3, 4],
                          [5, 6]])

tensor_B = torch.tensor([[7, 10],
                          [8, 11],
                          [9, 12]])

In [134]:
# torch.mm is the same as torch.matmul

torch.mm(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [135]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape using a **transpose**

A transpose switched the axis or dimensions of a given tensor

In [139]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [140]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [141]:
# The matrix multiplication works when tensor_B is transposed
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])